[package]
name = "advent_of_code_22"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10.5"
prime-factor = "0.4.3"
fast_paths = "0.2.0"

